# Generated by Django 2.0.4 on 2018-04-19 02:18

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('real_name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '后台用户',
                'verbose_name_plural': '后台用户',
                'ordering': ['-c_time'],
            },
            managers=[
                ('userObj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Network_Devices_Czy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(db_column='ip_address', max_length=32, unique=True)),
                ('username', models.CharField(db_column='username', max_length=128)),
                ('password', models.CharField(db_column='password', max_length=400)),
                ('super_password', models.CharField(blank=True, db_column='super_password', max_length=400)),
                ('device_name', models.CharField(db_column='device_name', max_length=128)),
                ('device_type', models.CharField(db_column='device_type', max_length=128)),
                ('device_vender', models.CharField(db_column='device_vender', max_length=128)),
                ('device_model', models.CharField(db_column='device_model', max_length=128)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '设备账号',
                'verbose_name_plural': '设备账号',
            },
            managers=[
                ('devObj', django.db.models.manager.Manager()),
            ],
        ),
    ]
