# Generated by Django 2.0.4 on 2018-04-19 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login_user',
            options={'ordering': ['-c_time'], 'verbose_name': '网站用户', 'verbose_name_plural': '网站用户'},
        ),
    ]
